galasa-dev/cli

- DockerfileCli
- tekton/task-galasactl-build.yaml
> switch cli image to alpine so we can use cat and echo

- Makefile
> standalone go programs

- DockerfileCli
> need a working directory for portfolios and throttle files

- pkg/cmd/runsPrepare.go
> rename to prepare

- README.md
> change docs for prepare

- pkg/cmd/runsSubmit.go
> exit 1 if tests have failed

- tekton/task-galasactl-build.yaml
> correct sed

- .gitignore
- pkg/cmd/runsSubmit.go
> add reports

- pkg/cmd/runsSubmit.go
> correct flag name

- tekton/pipe-galasactl-build.yaml
- tekton/prun-main-galasabld-build.yaml
- tekton/task-galasactl-build.yaml
- tekton/task-galasactl-release.yaml
> updated tekton files for releasing the cli to github

- tekton/pipe-snapshot-cli.yaml
> remove snapshot for the http image

- pkg/cmd/runsSubmit.go
> requestor and requesttype flags

- pkg/cmd/runsPrepare.go
- pkg/cmd/runsSubmit.go
- pkg/utils/testSelection.go
> add throttlefile and change logging for timestamps

- README.md
> remove things to do from readme

- cmd/galasactl/main.go
- pkg/api/api.go
- pkg/cmd/root.go
- pkg/cmd/runs.go
- pkg/cmd/runsPrepare.go
- pkg/cmd/runsSubmit.go
- pkg/utils/javaProperties.go
- pkg/utils/portfolio.go
- pkg/utils/testCatalog.go
- pkg/utils/testSelection.go
- pkg/utils/testStream.go
> correct formatting of progress after move to log

- pkg/cmd/runsSubmit.go
> remove extra blank line

- pkg/cmd/runsSubmit.go
> update message format

- DockerfileHttp
- httpd.conf
> correct path

- pkg/cmd/runsSubmit.go
Signed-off-by: Jade Carino <jade.carino@ibm.com>
> Change to galasactl runs submit to add XXXXX With Defects results

- Makefile
Signed-off-by: Will Yates <hobbit1983@gmail.com>
> add arm 64 support for m1

- pkg/cmd/runsSubmit.go
Signed-off-by: Jade Carino <jade.carino@ibm.com>
> Remove exit code for failures, if flag set

- README.md
> Added link on where to get the released/stable version of the built artifacts

- pkg/embedded/templates/galasahome/overrides.properties
- pkg/embedded/templates/projectCreate/parent-project/pom.xml
- pkg/embedded/templates/projectCreate/parent-project/test-project/src/main/java/TestExtended.java.template
Signed-off-by: Will Yates <hobbit1983@gmail.com>
> small tweaks to cli

- pkg/embedded/templates/projectCreate/parent-project/test-project/src/main/java/TestExtended.java.template
Signed-off-by: Will Yates <hobbit1983@gmail.com>
> add logging to sample test

- docs/generated/galasactl_project_create.md
- docs/generated/galasactl_runs_submit.md
- docs/generated/galasactl_runs_submit_local.md
- pkg/cmd/projectCreate.go
- pkg/cmd/runsSubmit.go
- pkg/runs/submitter.go
- respect progress report times, and default of features flag changed.
> mcobbett 1352 disable progress reporting

- build-locally.sh
- build.gradle
- pkg/embedded/embedded.go
- pkg/launcher/jvmLauncher.go
- pkg/launcher/jvmOutputProcessor.go
- test-locally.sh
> Use 0.26.0 boot jar

- README.md
> CLI README add gradle build details

- Makefile
- build-locally.sh
- docs/generated/errors-list.md
- docs/generated/galasactl_runs.md
- docs/generated/galasactl_runs_get.md
- pkg/cmd/runsGet.go
- pkg/cmd/runsSubmit.go
- pkg/errors/errorMessage.go
- pkg/formatters/summaryFormatter.go
- pkg/formatters/summaryFormatter_test.go
- pkg/runs/runsGet.go
- pkg/runs/runsGet_test.go
- pkg/utils/console.go
For https://github.com/galasa-dev/projectmanagement/issues/1405
> Add runs get to get a run by runname

- pkg/runs/runsGet.go
- pkg/utils/timeService.go
Signed-off-by: Eamonn Mansour <47121388+eamansour@users.noreply.github.com>
> Use UTC to fix time format issues on macOS

- pkg/formatters/detailsFormatter.go
- pkg/formatters/detailsFormatter_test.go
- pkg/formatters/rawFormatter.go
- pkg/formatters/rawFormatter_test.go
- pkg/formatters/runsFormatter.go
- pkg/formatters/summaryFormatter.go
- pkg/runs/runsGet.go
- pkg/runs/runsGet_test.go
- test-galasactl-ecosystem.sh
- Added raw formatter and unit tests
- created a new time parsing function to get more accurate duration
- moved some code from the formatters into runsFormatter code
- IVT test for raw formatter
- refactored time-related code in formatters
> raw formatter and improved duration calculation

- pkg/formatters/detailsFormatter.go
- pkg/formatters/detailsFormatter_test.go
- pkg/formatters/runsFormatter.go
- pkg/formatters/summaryFormatter.go
- pkg/formatters/summaryFormatter_test.go
- pkg/runs/runsGet_test.go
- test-galasactl-ecosystem.sh
- run result totals at end of summary and details formatter
- refactored code
- introduced constants
- unit tests
- minor updates
> record result totals

- pkg/formatters/detailsFormatter.go
- pkg/formatters/detailsFormatter_test.go
- pkg/formatters/runsFormatter.go
- pkg/formatters/summaryFormatter.go
- pkg/formatters/summaryFormatter_test.go
- pkg/runs/runsGet_test.go
- test-galasactl-ecosystem.sh
- dynamic results display so it only shows if the result type has more than one occurence
- added active label
> added active label, only show results if there are any of that kind

- pkg/launcher/jvmOutputProcessor.go
- pkg/launcher/testRun.go
> avoid two newlines in log

- test-galasactl-ecosystem.sh
Signed-off-by: Jade Carino <carino_jade@yahoo.co.uk>
> Added set -o pipefail into IVT script

- README.md
- docs/generated/errors-list.md
- docs/generated/galasactl_runs_download.md
- pkg/cmd/runsDownload.go
- pkg/errors/errorMessage.go
- pkg/runs/runsDownload.go
- pkg/runs/runsDownload_test.go
> Support the --destination flag on galasactl runs download

- pkg/embedded/templates/projectCreate/parent-project/pom.xml
> bump galasa maven plugin version

- docs/generated/galasactl_runs_get.md
- pkg/cmd/runsGet.go
- pkg/runs/runsGet.go
- pkg/runs/timeUnit.go
- pkg/runs/timeUnit_test.go
> Clarify documentation of the age parameter

- docs/generated/errors-list.md
- docs/generated/galasactl_runs_prepare.md
- docs/generated/galasactl_runs_submit.md
- docs/generated/galasactl_runs_submit_local.md
- pkg/cmd/runsPrepare.go
- pkg/cmd/runsSubmit.go
- pkg/cmd/runsSubmitLocal.go
- pkg/errors/errorMessage.go
- pkg/runs/testSelection.go
- pkg/runs/testSelection_test.go
Story: https://github.com/galasa-dev/projectmanagement/issues/1526
> changed error messages to provide more help and enforce required tags

- README.md
- build-locally.sh
- docs/generated/errors-list.md
- pkg/cmd/runsPrepare.go
- pkg/cmd/runsSubmit.go
- pkg/errors/errorMessage.go
- pkg/runs/testSelection.go
- pkg/runs/testSelection_test.go
- test-galasactl-ecosystem.sh
> test selection using a class requires a stream to be specified for remote runs submit and runs prepare

- docs/generated/errors-list.md
- pkg/errors/errorMessage.go
> fixed issue with error template not matching ordinal number. panic added to prevent this coding error in future

- Makefile
- README.md
- build-locally.sh
- test-galasactl-ecosystem.sh
- test-galasactl-local.sh
- test-locally.sh
This is now galasactl-darwin-x86_64.
> updated makefile and readme with new name for galasactl-darwin-amd64

- README.md
- docs/generated/galasactl_properties_get.md
- pkg/cmd/propertiesGet.go
- pkg/properties/propertiesGet.go
- pkg/properties/propertiesGet_test.go
- pkg/properties/propertyConverter.go
- pkg/properties/propertyConverter_test.go
story: [CLI: galasactl properties get does not support infixes#1577](https://github.com/galasa-dev/projectmanagement/issues/1577)
> infix functionality for properties get

- docs/generated/galasactl.md
- pkg/properties/propertiesDelete_test.go
- pkg/properties/propertyConverter.go
Story: https://github.com/galasa-dev/projectmanagement/issues/1577
> fiona 1566 cps properties

- docs/generated/errors-list.md
- docs/generated/galasactl_properties.md
- docs/generated/galasactl_properties_delete.md
- docs/generated/galasactl_properties_get.md
- docs/generated/galasactl_properties_set.md
- pkg/cmd/properties.go
- pkg/cmd/propertiesDelete.go
- pkg/cmd/propertiesGet.go
- pkg/cmd/propertiesSet.go
> tell cobra the name flag is mandatory for set and delete, but not get

- docs/generated/errors-list.md
- docs/generated/galasactl_properties.md
- docs/generated/galasactl_properties_delete.md
- docs/generated/galasactl_properties_get.md
- docs/generated/galasactl_properties_namespaces_get.md
- docs/generated/galasactl_properties_set.md
- docs/generated/namespaces_get.md
- pkg/cmd/properties.go
- pkg/cmd/propertiesDelete.go
- pkg/cmd/propertiesGet.go
- pkg/cmd/propertiesNamespace.go
- pkg/cmd/propertiesNamespaceGet.go
- pkg/cmd/propertiesSet.go
- test-scripts/properties-tests.sh
Continuation to story: [CLI ability to list available CPS namespaces#1600](https://github.com/galasa-dev/projectmanagement/issues/1600)
Signed-off-by: Fiona Ampofo <64271621+Akyiaa@users.noreply.github.com>
> refactoring namespaces command

- pkg/files/fileSystem_test.go
- pkg/runs/runsDownload_test.go
> Unit tests use windows file separator when on windows

- build.gradle
> Change order of maven repository lookup to make local versions take priority

- pkg/launcher/remoteLauncher.go
> reacting to openapi changes.

- .pre-commit-config.yaml
- .secrets.baseline
- build-locally.sh
- docs/generated/errors-list.md
- pkg/auth/authenticator_test.go
- pkg/auth/jwtCache_test.go
- pkg/cmd/commandCollection.go
- pkg/images/imageRenderer_test.go
- pkg/utils/bearerTokenFile_test.go
- pkg/utils/crypto_test.go
Story: https://github.com/galasa-dev/projectmanagement/issues/1884
> Detect secrets feature

- README.md
- gherkin-docs.md
- test-galasactl-ecosystem.sh
- test-galasactl-local.sh
- test-scripts/gherkin-runs-tests.sh
See https://github.com/galasa-dev/projectmanagement/issues/1858
- Add a local test which exercises a `Scenario Outline` and checks the output.
- Improve the existing Gherkin test to check that log statements actually appear.
> better gherkin tests which check the output, plus the Scenario Outline: syntax

- gherkin-docs.md
See story 1858 https://github.com/galasa-dev/projectmanagement/issues/1858
> Issue 1858 - better gherkin docs

- gherkin-docs.md
- pkg/embedded/templates/galasahome/cps.properties
- pkg/embedded/templates/galasahome/overrides.properties
> Issue 1708 - set the size of gherkin terminals

- .github/workflows/build.yml
- .github/workflows/pr-build.yml
For https://github.com/galasa-dev/projectmanagement/issues/1982
> Iss1982 - Add copyright and remove argo app param

- .github/workflows/build.yml
For https://github.com/galasa-dev/projectmanagement/issues/1996
> Iss1996 - Add report failed build job

- pkg/errors/errorMessage.go
- pkg/properties/properties.go
- pkg/properties/propertiesDelete_test.go
- pkg/properties/propertiesSet_test.go
- Refer to https://github.com/galasa-dev/projectmanagement/issues/2059
Signed-off-by: Aashir Siddiqui <aashir_sidiki@hotmail.com>
> CPS property name now accepts @ symbol

- pkg/utils/logRedirector.go
> remove a deprecated call usage for ioutil

- .github/workflows/build.yml
Changes following PR https://github.com/galasa-dev/galasa/pull/167
> Update WRITE_GITHUB_PACKAGES_USERNAME to var not secret

- pkg/launcher/jvmLauncher.go
- pkg/launcher/launcher.go
- pkg/launcher/launcherMock.go
- pkg/launcher/remoteLauncher.go
- pkg/launcher/remoteLauncher_test.go
- pkg/runs/jsonReporter_test.go
- pkg/runs/runTypes.go
- pkg/runs/submitter.go
- pkg/runs/yamlReporter_test.go
- test-scripts/run-single-test-remotely.sh
> submission id used to detect lost runs

- docs/generated/errors-list.md
- docs/generated/galasactl.md
- docs/generated/galasactl_streams.md
- docs/generated/galasactl_streams_get.md
- pkg/cmd/commandCollection.go
- pkg/cmd/streams.go
- pkg/cmd/streamsGet.go
- pkg/cmd/streamsGet_test.go
- pkg/cmd/streams_test.go
- pkg/errors/errorMessage.go
- pkg/streams/streams.go
- pkg/streams/streamsGet.go
- pkg/streams/streamsGet_test.go
- pkg/streams/streams_test.go
- pkg/streamsformatter/streamsFormatter.go
- pkg/streamsformatter/summaryFormatter.go
- pkg/streamsformatter/summaryFormatter_test.go
- pkg/streamsformatter/yamlFormatter.go
- pkg/streamsformatter/yamlFormatter_test.go
- Refer to https://github.com/galasa-dev/projectmanagement/issues/1615
- For YAML format refer to https://github.com/galasa-dev/projectmanagement/issues/1604
Signed-off-by: Aashir Siddiqui <aashir_sidiki@hotmail.com>
> CLI now supports streams command
