.gitignore
Makefile
build-locally.sh
go.mod
go.sum
pkg/utils/testStream.go
pkg/utils/testStream_test.go

This PR implements this story: https://github.com/galasa-dev/projectmanagement/issues/1236
----
Old output:
```
2022/11/07 12:37:07 Galasa CLI - Assemble tests
2022/11/07 12:37:07 Stream "XXXXX" is missing from ecosystem
```
New output:
```
2022/11/07 12:55:36 Galasa CLI - Assemble tests
2022/11/07 12:55:36 Stream "XXXXX" is not found in the ecosystem. Valid streams are: 'SIMBANK' 'DEVCAMP' 'EXAMPLE'. Try again using a valid stream, or ask your Galasa system administrator to add a new stream with the desired name.
```

better error message with unit tests

---

build-locally.sh

The script was not in the correct folder to do relative checking for a dependency.
Fixed.

CLI builds fail with error

---

README.md
docs/generated/errors-list.md
pkg/errors/errorMessage.go

This PR relates to story #projectmanagement/1235
It deals with the aspect that DNS resolution from within go programs always work over a VPN, and that the hostname needs adding to the `/etc/hosts` file.

Failing to resolve bootstrap URL better error message and doc limitation

---

README.md

@AaronJhaj Do we know the equivalent URLs for the officially-released/stable images/binaries ? 
@AaronJhaj Can we add similar comments to any of the other repositories, so it's easier for people to find built artifacts of the repo they are changing ?

usage instructions for docker and download url in readme

---

pkg/cmd/root.go
pkg/utils/logRedirector.go

When using --log option in `galasactl`, it appended to existing log files. Not that helpful.

galasactl log file should create anew and not append to existing

---

pkg/launcher/jvmLauncher.go
pkg/launcher/jvmLauncher_test.go

- local JVM runs have prefix L in their runid

mcobbett 1378 should use L prefix

---

build-locally.sh
docs/generated/errors-list.md
docs/generated/galasactl_runs_submit.md
docs/generated/galasactl_runs_submit_local.md
pkg/cmd/runsSubmit.go
pkg/errors/errorMessage.go
pkg/launcher/jvmLauncher.go
pkg/runs/submitter.go
pkg/runs/submitter_test.go
test-locally.sh

Addresses issue [#1389](https://github.com/galasa-dev/projectmanagement/issues/1389)

don't fail to launch if overrides file is not there

---

build-locally.sh
docs/generated/galasactl_project_create.md
pkg/cmd/projectCreate.go
pkg/cmd/projectCreate_test.go
pkg/embedded/templates/projectCreate/parent-project/obr-project/build.gradle.template
pkg/embedded/templates/projectCreate/parent-project/settings.gradle.template
pkg/embedded/templates/projectCreate/parent-project/test-project/bnd.bnd
pkg/embedded/templates/projectCreate/parent-project/test-project/build.gradle.template
pkg/embedded/templates/projectCreate/parent-project/test-project/src/main/build.gradle
test-locally.sh

(In progress)
For https://github.com/galasa-dev/projectmanagement/issues/1333
Main changes:
- Added `--maven` flag to allow Maven test projects to be created when running `galasactl project create` (this is the default option, so it does not need to be specified).
- Added `--gradle` flag to allow Gradle test projects to be created when running `galasactl project create`.
- Can specify both `--maven` and `--gradle` to create Maven and Gradle files in a test project.
- Added unit tests to cover both flags

Add --gradle and --maven flags to create Gradle and Maven test projects

---

build.gradle

Declaring compileClasspath inside the dependencies clause is not supported in versions of Gradle later than 7. Using implementation instead is supported in various levels of Gradle, I have tested this with 6.9.2, 7.1 and 8.0.1 and all worked.
Signed-off-by: Jade Carino <carino_jade@yahoo.co.uk>

Update gradle file dependencies to work with later versions of Gradle

---

build.gradle

Bumping to keep consistency between the version used in this repo and the build pipelines. Tested openapi client generation with this version and found no issues.
Signed-off-by: Eamonn Mansour <47121388+eamansour@users.noreply.github.com>

Bump openapi-generator-cli to 6.1.0

---

.gitignore
build-locally.sh
pkg/cmd/projectCreate.go
pkg/cmd/projectCreate_test.go
pkg/embedded/templates/projectCreate/parent-project/git-ignore.template
pkg/embedded/templates/projectCreate/parent-project/obr-project/build.gradle.template
pkg/embedded/templates/projectCreate/parent-project/settings.gradle.template
pkg/embedded/templates/projectCreate/parent-project/test-project/build.gradle.template
pkg/utils/fileGenerator.go

galasactl project create adds a .gitignore file

---

README.md
build-locally.sh
docs/generated/galasactl_local_init.md
docs/generated/galasactl_project_create.md
pkg/cmd/localInit.go
pkg/cmd/localInit_test.go
pkg/cmd/projectCreate.go
pkg/cmd/projectCreate_test.go
pkg/embedded/templates/m2/settings.xml
pkg/embedded/templates/projectCreate/parent-project/settings.gradle.template
pkg/utils/m2FolderCreator.go
pkg/utils/m2FolderCreator_test.go

this PR relates to story https://github.com/galasa-dev/projectmanagement/issues/1434

--development flag

---

README.md
pkg/cmd/projectCreate.go
pkg/cmd/projectCreate_test.go
pkg/embedded/templates/projectCreate/parent-project/test-project/build.gradle.template

I forgot to spec in the work item that the child test project's build.gradle would also need to be affected by the --development flag and include or not include the development.galasa.dev repository.
- Updates made to project create
- Updates to the build.gradle.template
- Updates to the tests
- Update to README.md
Signed-off-by: Jade Carino <carino_jade@yahoo.co.uk>

--development flag - continued

---

docs/generated/errors-list.md
pkg/cmd/localInit.go
pkg/cmd/projectCreate.go
pkg/cmd/runsGet.go
pkg/cmd/runsPrepare.go
pkg/cmd/runsSubmit.go
pkg/cmd/runsSubmitLocal.go
pkg/errors/errorMessage.go
pkg/utils/fileSystem.go
pkg/utils/fileSystemMock.go
pkg/utils/logRedirector.go
pkg/utils/logRedirector_test.go

This PR is created to address the issue raised in this bug report: https://github.com/galasa-dev/projectmanagement/issues/1451

make log redirector testable. log can't be a folder.

---

build-locally.sh
pkg/embedded/templates/projectCreate/parent-project/test-project/pom.xml
pkg/embedded/templates/projectCreate/parent-project/test-project/src/main/java/TestExtended.java.template

The generated testcase (Extended version) now creates a file within the RAS store.
This code relates to the following issue: https://github.com/galasa-dev/projectmanagement/issues/1336

Extended testcase now writes a file to the artifacts root in RAS

---

test-galasactl-ecosystem.sh

download test was failing as the log wa inconsistent so sometimes has "now running" and sometimes didn't. I have added a check to the number of artifacts so if the folder name has a timestamp, we check there are less than 10 artifacts downloaded as this is the minimum number of artifacts the finished test has

fix download ivt test

---

pkg/embedded/embedded.go

- Remove the offending log statement.
- Remove log which occurs if readTextFile fails. That error will already have been logged and a stack trace made available.
See [issue projectManagement#](https://github.com/galasa-dev/projectmanagement/issues/1530)

remove rogue log statement.

---

build-locally.sh
build.gradle
test-locally.sh

bump up the boot jar version and fix up scripts to read version dynamically from build.gradle

---

pkg/api/bootstrap.go

galasactl runs submit local now has the correct default file path for the bootstrap file on windows. This has been tested on a windows machine.

changed getDefaultBootstrapPath to work in strings rather than URLs

---

pkg/runs/humanReporter.go
pkg/runs/humanReporter_test.go

Story: [CLI test results summay is in random order.#1556](https://github.com/galasa-dev/projectmanagement/issues/1556)
- fixed the order in which tests show for human readable reports
- provided constant variables for results

fiona 1556 tests order

---

pkg/cmd/propertiesDelete.go
pkg/cmd/propertiesGet.go
pkg/cmd/propertiesSet.go

Related to https://github.com/galasa-dev/projectmanagement/issues/1566
The `--bootstrap` flag was not working correctly for properties commands since the correct bootstrap variable was not being used.

Fix --bootstrap flag for properties commands

---

build-locally.sh
pkg/cmd/factory.go
pkg/cmd/factoryMock.go
pkg/cmd/projectCreate_test.go
pkg/cmd/propertiesGet.go
pkg/cmd/propertiesNamespaceGet.go
pkg/cmd/root.go
pkg/cmd/root_test.go
pkg/cmd/runsDownload.go
pkg/cmd/runsGet.go
pkg/cmd/runsSubmit.go
pkg/cmd/runsSubmitLocal.go

- Separate consoles to collect output from cobra and the rest of the tools when running within unit tests.
- Unit tests can now get the mock console attached to stdout, separately to the one attached to stderr.

separate consoles to collect output for stdout/stderr

---

build-locally.sh
build.gradle
genapi.sh
generate.sh

CLI build locally doesn't depend on ../framework/openapi.yaml, but gets it from a dependency
it downloads.
It currently expects the openapi.yaml file to be in dev.galasa.framework.api.openapi
at the same version as the framework itself.
Once this PR is merged, we can change the automation to use the newly downloaded openapi.yaml file too.

CLI downloads the openapi.yaml rather than referring to ../framework/openapi.yaml

---

pkg/launcher/remoteLauncher.go

Be wary about using the value of a CPS property returned by the API in case it's nil.

be more safe when accessing cps property returned from the remote API

---

pkg/properties/propertiesDelete.go
pkg/properties/propertiesSet.go
test-galasactl-ecosystem.sh
test-scripts/properties-tests.sh
test-scripts/resources-tests.sh
test-scripts/runs-tests.sh

Currently `properties set` does not work for the `secure` namespace. However it works with other namespaces, eg `framework` and `ecosystem test`
This pr has an updated goal of getting the `test-galasactl-ecosystem.sh` working.

getting test-galasactl-ecosystem.sh to work

---

README.md
docs/generated/errors-list.md
pkg/auth/authLogin.go
pkg/auth/authLogin_test.go
pkg/auth/authProperties.go
pkg/auth/authProperties_test.go
pkg/cmd/authLogin.go
pkg/cmd/propertiesDelete.go
pkg/cmd/propertiesGet.go
pkg/cmd/propertiesNamespaceGet.go
pkg/cmd/propertiesSet.go
pkg/cmd/runsDownload.go
pkg/cmd/runsGet.go
pkg/cmd/runsPrepare.go
pkg/cmd/runsSubmit.go
pkg/errors/errorMessage.go
pkg/properties/propertiesGet_test.go
pkg/properties/propertiesSet_test.go
pkg/props/javaProperties.go

- Allow auth properties to be set into the environment as env variables
- Env vars override whatever is in the file
- File is not needed if all env vars are present
- Missing env variables are sourced from the file
- Any missing properties get complained about
- Error message says add them to file or environment variable
- readme updates
This relates to story [CLI auth galasactl.properties values overridden using environment variables#1713](https://github.com/galasa-dev/projectmanagement/issues/1713)

Allow auth properties as environment variables instead of always being within the galasactl.properties file

---

pkg/images/imageExpander_test.go
pkg/images/imageRenderer_test.go

Changes:
- Resolves test failures on different clients due to imperceptible variations in RGB values by comparing image pixels instead of bytes and using monochrome comparisons

Compare images by pixels instead of bytes

---

README.md
docs/generated/errors-list.md
pkg/auth/authLogin_test.go
pkg/auth/authProperties.go
pkg/auth/authProperties_test.go
pkg/embedded/templates/galasahome/galasactl.properties
pkg/errors/errorMessage.go

For https://github.com/galasa-dev/projectmanagement/issues/1744
Changes:
- Updated the auth property format to use `GALASA_TOKEN={token}:{clientId}`
- Removed client secret from auth properties and any tests that were focused on testing the client secret property

Update auth property format to GALASA_TOKEN and remove client secret from token

---

docs/generated/errors-list.md
pkg/errors/errorMessage.go

Information message reflects accepted response rather than OK.

Iss 1479 & 1685 - Updated the successful info message

---

pkg/cmd/runsDownload.go
pkg/errors/errorMessage.go
pkg/images/imageExpander.go
pkg/runs/runsDownload.go

I noticed that downloads were being rendered right at the end of the process.
When I downloaded a test which has multiple re-run attempts, I only saw one rendering of the images... because the '.' folder was being used.
I fixed it now to show this:
```
>../bin/galasactl-darwin-arm64 runs download --name C20339 --force        
GAL2501I: Downloaded 5 artifacts to folder 'C20339-1'
GAL2502I: Rendered 0 image files in folder 'C20339-1'
GAL2501I: Downloaded 5 artifacts to folder 'C20339-2'
GAL2502I: Rendered 0 image files in folder 'C20339-2'
GAL2501I: Downloaded 5 artifacts to folder 'C20339-3'
GAL2502I: Rendered 0 image files in folder 'C20339-3'
```
and this when I download a test which actually has images inside:
``` …
```

download a re-run folder, and it gets rendered images too.

---

test-galasactl-ecosystem.sh
test-scripts/calculate-galasactl-executables.sh
test-scripts/gherkin-runs-tests.sh
test-scripts/properties-tests.sh
test-scripts/resources-tests.sh
test-scripts/runs-tests.sh

For https://github.com/galasa-dev/projectmanagement/issues/1747
Changes:
- Update the default bootstrap URL to use the prod1 ecosystem instead of prod in CLI ecosystem test scripts

Replace prod URL with prod1 in ecosystem test scripts

---

pkg/cmd/runsSubmitLocal.go
pkg/launcher/remoteLauncher.go
pkg/launcher/remoteLauncher_test.go

Instead of using the framework.test.streams property, use a wider query to find all the test.stream.xxx.repo properties in the CPS... that gives the same list (one would hope)
Doing this means we shouldn't need to manually maintain the test.streams CPS property, which is a pain.
This is really a sticking plaster where what we should have is a REST service which delivers the streams as structures.
But if we can avoid people needing to maintain the test.streams value that would be a help.

remove the need for the framework test.streams cps property

---

pkg/images/imageExpander.go
pkg/images/imageFileWriter.go

Tom Slattery says we are still creating too much logging when rendering the image files.
Cutting it down even further.
Any errors are raised with lots of detail anyway I believe.
This PR contributes to this issue: CLI: Galsactl logs too much when rendering images during local test runs
[#1803](https://github.com/galasa-dev/projectmanagement/issues/1803)

Remove some logging statements. We get lots of detail if things fail anyway

---

pkg/embedded/templates/projectCreate/parent-project/obr-project/build.gradle.template

- Causes the generated gradle plugin to publish the test catalog as a maven artifact.

gradle templates should publish test catalog to maven repo

---

pkg/auth/authLogin.go
pkg/auth/authLogin_test.go
pkg/cmd/propertiesDelete.go
pkg/cmd/propertiesGet.go
pkg/cmd/propertiesNamespaceGet.go
pkg/cmd/propertiesSet.go
pkg/cmd/resourcesApply.go
pkg/cmd/runsCancel.go
pkg/cmd/runsDownload.go
pkg/cmd/runsGet.go
pkg/cmd/runsPrepare.go
pkg/cmd/runsReset.go
pkg/cmd/runsSubmit.go
pkg/properties/propertiesGet_test.go
pkg/properties/propertiesSet_test.go
pkg/resources/resourcesApplier.go
pkg/resources/resourcesApplier_test.go
test-scripts/runs-tests.sh

For https://github.com/galasa-dev/projectmanagement/issues/1473 and https://github.com/galasa-dev/projectmanagement/issues/1820
Changes:
- Now that authentication is mandatory, this PR removes the temporary code that was previously used to fall back to sending unauthenticated requests to the API server if a user could not authenticate with the ecosystem.
- Instead, an error will be returned informing the user that they will need to authenticate with the ecosystem.
- Changed the `requestor` value used in the ecosystem tests to use my ID temporarily to get the main builds passing again
- Fixed an issue where the "Authorization" header was not being set when running `galasactl resources` commands, causing 401 errors when contacting an API server requiring authentication

Remove temporary code and return an error instead of trying to send unauthenticated requests

---

pkg/errors/errorMessage.go
pkg/launcher/remoteLauncher.go
pkg/launcher/remoteLauncher_test.go

This PR is to fix issue [httpGet in remoteLauncher fails and no error message is logged.
#1824](https://github.com/galasa-dev/projectmanagement/issues/1824)

error from getcatalog is not lost now

---

README.md
docs/generated/errors-list.md
pkg/auth/authLogin.go
pkg/launcher/jvmLauncher.go
pkg/launcher/jvmLauncher_test.go
pkg/utils/bearerTokenFile.go
pkg/utils/bearerTokenFile_test.go

See 
[Local test run to be able to use remote CPS #1813](https://github.com/galasa-dev/projectmanagement/issues/1813)
## What changed
- The CLI looks at the bootstrap properties.
- If the framework.config.store value starts with 'galasacps' then the CLI gets the JWT (or fails if the user isn't logged-in).
- The JWT is passed to the launched JVM via a system property `GALASA_JWT`.

CLI supplies a JWT to a local launched test if framework.config.store bootstrap value starts with galasacps

---

build.gradle

This change is needed in order to be able to boot from galasa-boot-0.34.0.jar which has been updated during the changes for the commons-compress upgrade.

bumped galsaa-boot version to 0.34.0 to match commons-compress changes in framework

---

test-scripts/runs-tests.sh

Resolves main build failures now that the Galasadelivery's ID is used in the GALASA_TOKEN property in automation.

Change requestor to galasadelivery ID

---

pkg/auth/authenticator.go
pkg/auth/authenticator_test.go

See https://github.com/galasa-dev/projectmanagement/issues/1865
- Updated the OpenAPI client method used to contact the `/auth/tokens` endpoint to create new auth tokens

Use /auth/tokens route to create tokens instead of /auth

---

docs/generated/errors-list.md
pkg/runs/runsDownload.go

Vulnerability reported by IBM-internal code scanning tool.
- Best not to use the reflect library if possible, as that can be the source of some problems.
- Removed the use of the reflect call.

vulerability reported. Removing printf content to zap it

---

pkg/embedded/templates/projectCreate/parent-project/pom.xml

Follow-on from changes in https://github.com/galasa-dev/maven/pull/118
Note: Builds for this PR will fail until the above PR is merged
- Bumped the Galasa maven plugin to 0.34.0 in the pom.xml template for `galasactl project create` commands

Bump maven plugin to 0.34.0

---

pkg/launcher/remoteLauncher.go
pkg/launcher/remoteLauncher_test.go

This is to remove the dependency to the accessCPS.java class in the framework and to ensure that the same endpoint is used by all cli callouts for properties

Switched call for remote launcher to get streams from new api endpoints

---

docs/generated/galasactl_auth_tokens_delete.md
docs/generated/galasactl_properties_set.md
pkg/cmd/authTokensDelete.go
pkg/cmd/propertiesSet.go

See https://github.com/galasa-dev/projectmanagement/issues/1729
And changes made in https://github.com/galasa-dev/cli/pull/154
- Changed the mention of "deleting" a token to "revoking" a token for consistency with the `auth tokens delete` documentation
- Added missing shorthand `-v` flag for `properties set` since all other flags have shorthand equivalents but `--value` (e.g. `--name` has `-n`, `--namespace` has `-s`)

Update help text for --tokenid flag in `auth tokens delete` and add `-v` shorthand for `--value` in the properties set command

---

build-locally.sh
pkg/embedded/templates/galasahome/bootstrap.properties

Someone asked how to change the prefix of the run name for a local test.
The answer is to set a property into the bootstrap.properties file.
- Added a comment which documents this property so it's easier for people to find (if they have used `galasactl local init`

added bootstrap property commented-out for documentation

---

pkg/embedded/templates/galasahome/cps.properties
pkg/embedded/templates/galasahome/overrides.properties
test-scripts/test-local-run-remote-cps.sh

See issue [#1899](https://github.com/galasa-dev/projectmanagement/issues/1889)
- Added extra property to the generated cps.properties (commented-out) which turns on/off caching.
- Added more tests which try with and without a cache.

mcobbett 1889 rest cps cache

---

pkg/properties/propertiesGet_test.go
pkg/properties/propertiesSet.go
pkg/properties/propertiesSet_test.go

This is to ensure that the error message from the server is being displayed to the user properly along with the status code

updated properties set command to respond with Server errors in error messages

---

build.gradle
pkg/embedded/templates/projectCreate/parent-project/obr-project/build.gradle.template
pkg/embedded/templates/projectCreate/parent-project/test-project/build.gradle.template

[1652](https://github.com/galasa-dev/projectmanagement/issues/1652)
To support the latest versions of gradle for building galasa

updated templates to support gradle 8.x and bumped up boot jar version

---

.github/workflows/build.yml
.github/workflows/pr-build.yml

- Story https://github.com/galasa-dev/projectmanagement/issues/1965
- Upgrade Java version to 17
- Upgrade Gradle version to 8.9
- Upload Gradle log as artefact to workflow
- Story https://github.com/galasa-dev/projectmanagement/issues/1966
- Trigger Isolated workflow at end of successful CLI workflow
- Story https://github.com/galasa-dev/projectmanagement/issues/1958
- Parameterise the CLI workflow to run on other branches other than main for releases/branch builds 
Combining these changes into one PR to avoid lots of build triggering.

Update CLI workflow for stories 1966, 1965 and 1958

---

pkg/runs/runsDownload_test.go
pkg/runs/runsGet.go
pkg/runs/runsGet_test.go

See https://github.com/galasa-dev/projectmanagement/issues/1921
- Instead of iterating through page numbers, `runs get` now uses the cursor provided in responses from `/ras/runs` to go through pages of run results

Update runs get to use cursor-based pagination

---

.secrets.baseline
pkg/launcher/jvmLauncher.go
pkg/launcher/jvmLauncher_test.go

Overrides not being set properly. In my environment, it's because the `GALASA_HOME` environment variable, or the `--galasahome` parameter on `galasactl` is not being passed correctly to the JVM.
See the story driving this investigation here: https://github.com/galasa-dev/projectmanagement/issues/1916

JVM launching -D parameters should be passed before the -jar parameter to have any effect

---

pkg/propertiesformatter/propertyFormatter.go
pkg/propertiesformatter/propertyFormatter_test.go
pkg/propertiesformatter/rawFormatter.go
pkg/propertiesformatter/summaryFormatter.go
pkg/propertiesformatter/yamlFormatter.go

In order to cope with some .md markdown text we need the set/get properties to work well with properties which have newlines inside.
- super-long values can be set, but when displayed in summary view they get cropped with a `...(cropped)` string at the end. Newlines are replaced with `\n`.
- raw format shows new lines replaced with `\n`
- yaml format creates decent yaml, and accepts yaml with multiple-line input such as this:
```
piVersion: galasa-dev/v1alpha1
kind: GalasaProperty
metadata:
namespace: mcobbett6
name: markdown.test.1
data:
value: |-
This is a line of text in the this is a longer description
which spans multiple lines and 
And happends to be very long.
Here is an example of a list
- one
- two
- three
And a [link here](https://galasa.dev)
```

CLI should handle long and multi-line property values better.

---

dockerfiles/dockerfile.galasactl

`bash` is needed to be able to run the CLI testing scripts from within the galasactl docker images. alpine does not have bash available, just sh.

Change the CLI's base image to ubuntu so it has bash

---

.github/workflows/build.yml

Trigger is now following the successful test-cli-ecosystem-commands Tekton pipeline (see [PR](https://github.com/galasa-dev/automation/pull/608)).

Remove isolated trigger at end of Main build workflow

---

.secrets.baseline
gherkin-docs.md

I found out how to use the credentials with 3270 gherlin syntax by looking at the code.
Documenting so that others might get value out of this un-documented functionality.

extra instructions for using credentials with 3270 gherkin

---

build-locally.sh

build locally script on linux should not leave timestamp in detect secrets baseline file

---

.secrets.baseline
pkg/cmd/runsSubmit.go
pkg/cmd/runsSubmitLocal.go
pkg/launcher/jvmLauncher.go
pkg/launcher/jvmLauncher_test.go
pkg/launcher/localTest.go
pkg/properties/propertiesGet.go
pkg/runs/runsDownload_test.go
pkg/runs/submitter.go
pkg/runs/submitter_test.go
pkg/spi/timeService.go
pkg/spi/timedSleeper.go
pkg/utils/timeService.go
pkg/utils/timeServiceMock.go
pkg/utils/timedSleeper.go
test-scripts/run-single-test-remotely.sh

While investigating https://github.com/galasa-dev/projectmanagement/issues/2009 I noted that the CLI tool didn't exit the moment the last test completed. 
It used to but at some point it stopped doing that.
It turns out that 2 timer services were being created. One thread went to sleep on one, and the other thread woke up on the other. So the interrupt event never woke the sleeping thread.
Solution: Use a single sleep service, and separate the sleeper service from the time service so it's less likely in the future.
Also, using the golang select... and time.After(delay) is the recommended way of doing this stuff as of Golang 1.23. What I've coded does work, but prior to 1.23 may result in a timer resource leakage.
We need to uplift the golang requirement to 1.23 next to avoid any resource …

mcobbett exit immediately when all tests done

---

pkg/users/usersGet_test.go

Something changed in the rest interface `login_id` is now `login-id`.
Updating the unit tests to expect the new response.

generated code changed. Unit test needs to change also

---

build.gradle

Related to https://github.com/galasa-dev/galasa/pull/15
Note: Builds for this PR will fail until https://github.com/galasa-dev/galasa/pull/15 is delivered

Bump galasa-boot to 0.38.0

---

dockerfiles/dockerfile.galasactl-executables

See https://github.com/galasa-dev/projectmanagement/issues/2057
httpd:2.4.59 contains several vulnerabilities, so switching over to use httpd:alpine instead.

Use httpd:alpine image in galasactl-executables dockerfile

---

pkg/cmd/projectCreate.go
pkg/cmd/projectCreate_test.go
pkg/embedded/templates/projectCreate/parent-project/obr-project/build.gradle.template
pkg/embedded/templates/projectCreate/parent-project/pom.xml
pkg/embedded/templates/projectCreate/parent-project/test-project/build.gradle.template
set-version.sh

Every release will bump the version of the maven and gradle files up we need to use.
Similarly, a different version of the galasa BOM needs to be referred to in test code.

set-version.sh should set version of boot jar also

---

pkg/runs/runsConverter.go
pkg/runs/runsConverter_test.go
pkg/runs/runsGet.go
pkg/runs/submitter.go
pkg/runsformatter/summaryFormatter.go
pkg/utils/timedSleeper.go
test-galasactl-ecosystem.sh
test-scripts/auth-tests.sh
test-scripts/runs-tests.sh

https://github.com/galasa-dev/projectmanagement/issues/2049
The actual problem: The formatter thought '' (blank) was a custom label for the results.
If there were 30 tests with a '' result label, those 30 tests were shown 30 times.
Unit test added to verify that custom labels only get returned once.
Seems to work much better now.

massive amounts of duplicates shown by formatter due to labels being duplicated

---

README.md

I want to see at a glance whether the main build is currently working or not.
Adding a badge reference into the readme so it's obvious to the reader.

add build badge to the readme

---

pkg/cmd/commandCollection.go

- Errors were being overwritten before being checked if the error is present or not. With this change, the flow of the program will check for errors after every step and will return the relevant error at relevant stage.
Signed-off-by: Aashir Siddiqui <aashir_sidiki@hotmail.com>

Enhanced error handling while creating commands

---

.github/workflows/build.yml

For https://github.com/galasa-dev/projectmanagement/issues/2085
Using secret names that are specific to the Galasa team means that when users fork this repository and set secrets in their forked repository, they have to set it to the same name which being Galasa specific, doesn't make sense. Updating the secret names to be more general so it makes sense for forked repos. Also removing the hard coded use of the `galasa-team` user as forks won't/shouldn't use this user.

Change secret names to non Galasa specific so relevant for forks

---

pkg/launcher/jvmOutputProcessor.go
pkg/utils/crlf.go
pkg/utils/crlf_test.go

See issues [log.info crops last line of input, but not in the run.log #2088](https://github.com/galasa-dev/projectmanagement/issues/2088)
When the string being logged has a CR, LF, or CRLF combination, it doesn't get written out as a /n by default.

Log messages may have CRLF or LF or CR characters. All converted to \n prior to logging to console

---

Makefile
build-locally.sh
build.gradle
set-galasa-boot-version.sh
set-version.sh
test-locally.sh

For https://github.com/galasa-dev/projectmanagement/issues/2084
- Remove hard coded versions from the CLI's dependencies as it should get them from dev.galasa.platform.
- Now that all Galasa versions are kept the same, replaced "galasaBootJarVersion" and "galasaFrameworkVersion" with just one "galasaVersion"
- Updated Makefile, build locally, test locally, and set version scripts to support the above change
- Add upgrade of the dev.galasa.platform into the set-version script
**Important**: The build of this PR will fail until https://github.com/galasa-dev/galasa/pull/118 is merged and has been deployed, as the CLI won't be able to find its artifacts in the Platform yet.

Iss2084 - Use Platform versions for CLI dependencies

---

pkg/api/bootstrap.go
pkg/auth/authTokensDelete.go
pkg/auth/authTokensGet.go
pkg/auth/authenticator.go
pkg/errors/errorMessage.go
pkg/errors/galasaAPIError.go
pkg/errors/galasaAPIError_test.go
pkg/launcher/remoteLauncher.go
pkg/properties/propertiesDelete.go
pkg/properties/propertiesGet.go
pkg/properties/propertiesNamespaceGet.go
pkg/properties/propertiesSet.go
pkg/resources/resourcesApplier.go
pkg/runs/resultParameterChecker.go
pkg/runs/runsCancel.go
pkg/runs/runsDownload.go
pkg/runs/runsGet.go
pkg/runs/runsReset.go
pkg/runs/submitter.go
pkg/spi/timeService.go
pkg/users/usersGet.go

See https://github.com/galasa-dev/projectmanagement/issues/2072
In order to capture errors related to rate limiting so that functions can be retried, the HTTP response code needs to be included in the GalasaError struct along with causes so that wrapped errors can also be identified properly.
- Added status code and error cause to the GalasaError struct and updated existing error creation to include status codes and causes where available
- Revisited response body closure in commands
- Runs get loops were not closing HTTP response bodies, so updated functions to make sure they are being closed

Add http status codes and causes to errors related to API server comms

---

.secrets.baseline
pkg/users/usersGet.go
pkg/users/usersGet_test.go
pkg/usersformatter/summaryFormatter.go
pkg/usersformatter/summaryFormatter_test.go
pkg/usersformatter/usersformatter.go

See issue https://github.com/galasa-dev/projectmanagement/issues/2071

CLI displays user roles when users are shown

---

docs/generated/errors-list.md
pkg/cmd/usersSet.go
pkg/errors/errorMessage.go
pkg/users/usersDelete.go
pkg/users/usersDelete_test.go
pkg/users/usersSet.go
pkg/users/usersSet_test.go

After doing more ad-hoc testing of the galasactl tool, I noted that the errors didn't have much detail inside.
Added code to decode the failures, reading and parsing the json and showing that to the user.
eg: `Instead of Could not update user 'mike' because you don't have permissions.` To something more like `Instead of Could not update user 'mike' because you don't have permissions. Http code from the server was 403. Error message from the server was: GAL5140E: Failed to update the role of a user record. The requestor is not allowed to change their own user role.`... not exact wording but that's the sort of thing which changes here.

better handling of 'galasactl users set' failures.

---

pkg/cmd/users.go
pkg/cmd/usersDelete.go

Solves bug [galasactl users delete with no login id specified deleted a user ! #2118](https://github.com/galasa-dev/projectmanagement/issues/2118)

login-id flag is now mandatory where it needs to be.

---

dockerfiles/dockerfile.galasactl
dockerfiles/dockerfile.galasactl-executables

For https://github.com/galasa-dev/projectmanagement/issues/1888
Replacing references to images stored in Harbor with GHCR now they have been moved over to our "docker proxy cache". Harbor has been experiencing unexplained issues so pulling/pushing images there has been failing, and so PR builds have been failing sporadically all day. Moving our regularly used based images to GHCR removes the chance for these outages which affect our delivery.
&
As part of another story, to give the galasactl-x86_64 image access to bash, the FROM image of the image was updated from Alpine to Ubuntu. Since then this has broken the command to add a user and group of galasa as the syntax used in the Dockerfile is for Alpine Linux, not Ubuntu. In Ubuntu, adduser works differently, and useradd and groupadd …

Iss1888 - Reference images in GHCR "docker proxy" instead of Harbor & fix broken adduser/addgroup for 'galasa'

---

pkg/launcher/jvmLauncher_test.go

Intermittent test failures spotted. See issue [Intermittent CLI Build failure #2146](https://github.com/galasa-dev/projectmanagement/issues/2146)
Not 100% sure why it failed, but it seemed to be in the json->object serialisation inflation code in the client... when it expected a group to be present.
Adding it to the static test data in the hope that it fixes it. If not we'll have to raise it again.

json test structure didn't contain group information. May be making intermittent failures

---

.github/workflows/build.yml
.github/workflows/pr-build.yml
test-galasactl-ecosystem.sh
test-scripts/auth-tests.sh
test-scripts/calculate-galasactl-executables.sh
test-scripts/gherkin-runs-tests.sh
test-scripts/properties-tests.sh
test-scripts/resources-tests.sh
test-scripts/runs-tests.sh

We temporarily need to stop testing on the prod1 service.
This set of changes points the CLI testing scripts at the ecosystem1 service instead of prod1. This is now possible since we have replicated the CoreManagerIVT and made it available on ecosystem1 with a new test stream.
However, there is no need to move back to prod1 even once we are told we can. This has removed the need to call into Tekton then come back to GH Actions again.
**Note:** the function in the runs testing script to test `runs reset` has been temporarily commented out as the CoreManagerIVT we are now running on ecosystem1 is too fast and doesn't give a sufficient time window to reset it. Mike suggests creating a new test case that simply has a sleep for this purpose so we can test runs reset.

Move CLI testing to ecosystem1

---

pkg/runs/runTypes.go
pkg/runs/submitter.go

See story https://github.com/galasa-dev/projectmanagement/issues/2167

Add initial workaround to find lost runs in the RAS before marking them as lost

---

pkg/runs/submitter.go

Try running the latest galasactl against a system which doesn't set the submission id, or return it in the response payload to the launch request over REST.
It panics with a null pointer exception. Because the submission ID wasn't set.
Added an 'if' so that it's more tolerant. This would be the case if someone uses the galasactl tool to launch tests on an older non-0.40.0 system.

galasactl can launch tests on old service without a submission id being set.

---

pkg/launcher/jvmLauncher.go

Galasa client should not set the submission id itself, but should only get one from a server-side response.

galasactl should not set submission id - it should come from the server or remain blank

---

README.md
docs/generated/errors-list.md
docs/generated/galasactl.md
docs/generated/galasactl_monitors.md
docs/generated/galasactl_monitors_get.md
pkg/cmd/commandCollection.go
pkg/cmd/monitors.go
pkg/cmd/monitorsGet.go
pkg/cmd/monitorsGet_test.go
pkg/cmd/monitors_test.go
pkg/errors/errorMessage.go
pkg/monitors/monitors.go
pkg/monitors/monitorsGet.go
pkg/monitors/monitorsGet_test.go
pkg/monitorsformatter/monitorsFormatter.go
pkg/monitorsformatter/summaryFormatter.go
pkg/monitorsformatter/summaryFormatter_test.go
pkg/monitorsformatter/yamlFormatter.go
pkg/monitorsformatter/yamlFormatter_test.go

See https://github.com/galasa-dev/projectmanagement/issues/2067
Note: Builds for this PR will fail until the openapi changes in https://github.com/galasa-dev/galasa/pull/237 are delivered.
- Added `galasactl monitors get` command to get monitors from a Galasa service with an optional `--name` flag to get a specific monitor by its name

Add monitors get command
